name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test1-1
      id: test1-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-1
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input1.txt
        input: ''
        expected-output: '39'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-2
      id: test1-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-2
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input2.txt
        input: ''
        expected-output: '33'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-3
      id: test1-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-3
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input3.txt
        input: ''
        expected-output: '32626'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-4
      id: test1-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-4
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input4.txt
        input: ''
        expected-output: '44042'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-5
      id: test1-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-5
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input5.txt
        input: ''
        expected-output: '266'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-6
      id: test1-6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-6
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input6.txt
        input: ''
        expected-output: '30942'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-7
      id: test1-7
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-7
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input7.txt
        input: ''
        expected-output: '30048'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-8
      id: test1-8
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-8
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input8.txt
        input: ''
        expected-output: '46000'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-9
      id: test1-9
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-9
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input9.txt
        input: ''
        expected-output: '29609'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-10
      id: test1-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-10
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input10.txt
        input: ''
        expected-output: '6365'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-11
      id: test1-11
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-11
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input11.txt
        input: ''
        expected-output: '10031'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-12
      id: test1-12
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-12
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input12.txt
        input: ''
        expected-output: '12211'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-13
      id: test1-13
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-13
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input13.txt
        input: ''
        expected-output: '25809'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-14
      id: test1-14
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-14
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input14.txt
        input: ''
        expected-output: '22909'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-15
      id: test1-15
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-15
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input15.txt
        input: ''
        expected-output: '29982'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-16
      id: test1-16
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-16
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input16.txt
        input: ''
        expected-output: '4519'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-17
      id: test1-17
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-17
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input17.txt
        input: ''
        expected-output: '19927'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-18
      id: test1-18
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-18
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input18.txt
        input: ''
        expected-output: '40151'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-19
      id: test1-19
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-19
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input19.txt
        input: ''
        expected-output: '3057'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test1-20
      id: test1-20
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test1-20
        setup-command: ''
        command: python3 problema1.py < inputs/problema1_input20.txt
        input: ''
        expected-output: '3485'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-1
      id: test2-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-1
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input1.txt
        input: ''
        expected-output: '8'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-2
      id: test2-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-2
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input2.txt
        input: ''
        expected-output: '2'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-3
      id: test2-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-3
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input3.txt
        input: ''
        expected-output: '34'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-4
      id: test2-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-4
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input4.txt
        input: ''
        expected-output: '13'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-5
      id: test2-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-5
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input5.txt
        input: ''
        expected-output: '3'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-6
      id: test2-6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-6
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input6.txt
        input: ''
        expected-output: '5'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-7
      id: test2-7
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-7
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input7.txt
        input: ''
        expected-output: '3'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-8
      id: test2-8
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-8
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input8.txt
        input: ''
        expected-output: '652'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-9
      id: test2-9
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-9
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input9.txt
        input: ''
        expected-output: '210'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: test2-10
      id: test2-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test2-10
        setup-command: ''
        command: python3 problema2.py < inputs/problema2_input10.txt
        input: ''
        expected-output: '1129'
        comparison-method: exact
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1-1_RESULTS: "${{steps.test1-1.outputs.result}}"
        TEST1-2_RESULTS: "${{steps.test1-2.outputs.result}}"
        TEST1-3_RESULTS: "${{steps.test1-3.outputs.result}}"
        TEST1-4_RESULTS: "${{steps.test1-4.outputs.result}}"
        TEST1-5_RESULTS: "${{steps.test1-5.outputs.result}}"
        TEST1-6_RESULTS: "${{steps.test1-6.outputs.result}}"
        TEST1-7_RESULTS: "${{steps.test1-7.outputs.result}}"
        TEST1-8_RESULTS: "${{steps.test1-8.outputs.result}}"
        TEST1-9_RESULTS: "${{steps.test1-9.outputs.result}}"
        TEST1-10_RESULTS: "${{steps.test1-10.outputs.result}}"
        TEST1-11_RESULTS: "${{steps.test1-11.outputs.result}}"
        TEST1-12_RESULTS: "${{steps.test1-12.outputs.result}}"
        TEST1-13_RESULTS: "${{steps.test1-13.outputs.result}}"
        TEST1-14_RESULTS: "${{steps.test1-14.outputs.result}}"
        TEST1-15_RESULTS: "${{steps.test1-15.outputs.result}}"
        TEST1-16_RESULTS: "${{steps.test1-16.outputs.result}}"
        TEST1-17_RESULTS: "${{steps.test1-17.outputs.result}}"
        TEST1-18_RESULTS: "${{steps.test1-18.outputs.result}}"
        TEST1-19_RESULTS: "${{steps.test1-19.outputs.result}}"
        TEST1-20_RESULTS: "${{steps.test1-20.outputs.result}}"
        TEST2-1_RESULTS: "${{steps.test2-1.outputs.result}}"
        TEST2-2_RESULTS: "${{steps.test2-2.outputs.result}}"
        TEST2-3_RESULTS: "${{steps.test2-3.outputs.result}}"
        TEST2-4_RESULTS: "${{steps.test2-4.outputs.result}}"
        TEST2-5_RESULTS: "${{steps.test2-5.outputs.result}}"
        TEST2-6_RESULTS: "${{steps.test2-6.outputs.result}}"
        TEST2-7_RESULTS: "${{steps.test2-7.outputs.result}}"
        TEST2-8_RESULTS: "${{steps.test2-8.outputs.result}}"
        TEST2-9_RESULTS: "${{steps.test2-9.outputs.result}}"
        TEST2-10_RESULTS: "${{steps.test2-10.outputs.result}}"
      with:
        runners: test1-1,test1-2,test1-3,test1-4,test1-5,test1-6,test1-7,test1-8,test1-9,test1-10,test1-11,test1-12,test1-13,test1-14,test1-15,test1-16,test1-17,test1-18,test1-19,test1-20,test2-1,test2-2,test2-3,test2-4,test2-5,test2-6,test2-7,test2-8,test2-9,test2-10
